### ISSUE TITLE
Decide on rough design for homepage

### ISSUE THREAD

**Issue by khdelphine** [tulibraries/VIVO#17]
Including positioning of RSS feed and other elements

**Comment by anniekj** [comment]
Here's my mock up! Apologies for the low-tech nature of it...I don't have Photoshop on this computer. The basic idea is to incorporate a scrolling news feed, similar to what Griffith Experts does:
https://drive.google.com/a/temple.edu/file/d/0BzpJdfujYNMxR0EtWElrV2VzSnM/view?usp=sharing

**Comment by khdelphine** [comment]
It looks good to me.  Thanks, Annie!

Now the developers have to tell us whether or not these suggestions are all easily implementable.  If it is not the case, Steven & Tim, don't hesitate to change parts of the design to increase ease of implementation.

Later on, past the demo, we could go back to the more difficult pieces, and decide if they would be worth spending more time on.

**Comment by khdelphine** [comment]
I just added Tim and Steven as assignees.
