### ISSUE TITLE
Testing the Temple News RSS feed on the home page

### ISSUE THREAD

**Issue by relaxing** [tulibraries/VIVO#5]

**Comment by relaxing** [comment]
scholars.duke.edu - working example
http://news.temple.edu/rss  - temple news feeds

**Comment by skng5** [comment]
Issue moved to [tulibraries/tuvivo_theme #1](https://github.com/tulibraries/tuvivo_theme/issues/1) via [**ZenHub**](https://www.zenhub.com/)
